
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour?useSSL=false
    username: root
    password: lotterygroup
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
server:
  port: 1200